### ISSUE TITLE
Error en el formato del atributo "monto", que se manda a la API

### ISSUE THREAD

**Issue by matiasalvarez87** [decidir/plugin-magento2-v2#2]
En la **clase**: [Payment.php](https://github.com/decidir/plugin-magento2-v2/blob/master/Decidir/SpsDecidir/Model/Payment.php)

**Línea 294**: `"amount" => number_format($amount, 2),`

Se esta utilizando la función `number_format`, que por defecto como menciona la [documentación oficial de PHP](http://php.net/manual/en/function.number-format.php) funciona de la siguiente manera. 

> If only one parameter is given, number will be formatted without decimals, but with a comma (",") between every group of thousands.

O sea, que por defecto se utiliza el caracter `,` como separador de los miles. 

**Esto genera que se manden los montos de las ordenes en un formato incorrecto.** A continuación van los logs de una implementación con una orden de $1730. 

_(Se eliminaron algunos atributos de los arrays por temas de seguridad, estos están marcados como `...`)_

```
[2017-11-24 12:17:47] main.DEBUG: DECIDIR2 - MODEL PAYMENT - InfoOperacion: Array
(
    [detalles_pago] => Pago realizado con AMERICAN EXPRESS y BANCO DE GALICIA Y BUENOS AIRES S.A. en 1 cuota fija de $1.730,00 - TEA: 0 % - CFT: 0
    [quote_id] => 
    [bin] => ...
    [tarjeta_sps] => 65
    [cuota] => 1
    [decidir_id_transaccion] => 
    [holderName] => ...
    [lastDigits] => ...
    [expirationMonth] => 5
    [expirationYear] => 18
    [tokenPago] => ...
    [tarjeta_id] => 65
    [bancoId] => 2
    [planPago] => 7
)
 {"is_exception":false} []
[2017-11-24 12:17:47] main.DEBUG: DECIDIR2 - MODEL PAYMENT - pagar - Data: Array
(
    [site_transaction_id] => T000000050
    [token] => ...
    [user_id] => 6
    [payment_method_id] => 65
    [amount] => 1,730.00
    [bin] => 371593
    [currency] => ARS
    [installments] => 1
    [description] => Orden T000000050
    [payment_type] => single
    [sub_payments] => Array
        (
        )
    [fraud_detection] => Array
        (
        )
    [site_id] => ...
)
 {"is_exception":false} []
[2017-11-24 12:17:50] main.DEBUG: DECIDIR2 - MODEL PAYMENT - pagar respuesta: Decidir\Payment\PaymentResponse Object
(
    [dataResponse:protected] => Array
        (
            [id] => 2904841
            [site_transaction_id] => T000000050
            [token] => ...
            [customer] => 
            [payment_method_id] => 65
            [bin] => 371593
            [amount] => 100
            [currency] => ars
            [installments] => 1
            [payment_type] => single
            [sub_payments] => Array
                (
                )
            [status] => approved
            [confirmed] => 
            [status_details] => 
            [date] => 2017-11-24T12:17Z
            [site_id] => 
            [establishment_name] => 
            [fraud_detection] => Array
                (
                    [status] => 
                )
            [aggregate_data] => 
            [pan] => 
        )
    [field_required:Decidir\Data\AbstractData:private] => 
    [ignoredFields:Decidir\Data\AbstractData:private] => Array
        (
            [0] => site_id
        )
)
(
    [tokens:protected] => 
    [dataResponse:protected] => Array
        (
            [tokens] => Array
                (
                )

        )

    [field_required:Decidir\Data\AbstractData:private] => 
    [ignoredFields:Decidir\Data\AbstractData:private] => Array
        (
            [0] => site_id
        )

)
```

Como se puede ver en este log el plugin de Decidir esta enviando el monto con el siguiente formato: `[amount] => 1,730.00`. **La respuesta de la API considera este número como $1, ya que devuelve el atributo `[amount] => 100`**. Lo dos últimos ceros representan los decimales. 

En la [documentación de la API de Decidir](https://decidir.gitbooks.io/documentacion/content/ComoMeIntegro/FlujoTransaccional/PedidoAutorizacion/Requerimiento/index.html), la documentación especifica que no se tiene que incluir el separador de miles. 

**MONTO**: Importe en Pesos de la transacción.
> Numérico con 9 dígitos con hasta 2 decimales 999999[.CC] Usando el punto como separador de decimales. No se permiten comas, ni como separador de miles ni como separador de decimales.

Por lo tanto:
`$ 125,38` -> debería ser enviado como `125.38`
`$ 1.325,38` -> debería ser enviado como `1325.38`

**Comment by matiasalvarez87** [comment]
Relacionado a este mismo tema de formato de números, hay varios lugares en donde se utiliza esta función sin ningún argumento extra:

* https://github.com/decidir/plugin-magento2-v2/blob/master/Decidir/SpsDecidir/Observer/Devolucion.php#L144
* https://github.com/decidir/plugin-magento2-v2/blob/master/Decidir/AdminPlanesCuotas/Model/Descuento.php#L99
* https://github.com/decidir/plugin-magento2-v2/blob/master/Decidir/AdminPlanesCuotas/Model/Descuento.php#L106
* https://github.com/decidir/plugin-magento2-v2/blob/master/Decidir/AdminPlanesCuotas/Model/Descuento.php#L107
* https://github.com/decidir/plugin-magento2-v2/blob/master/Decidir/AdminPlanesCuotas/Model/Descuento.php#L108
* https://github.com/decidir/plugin-magento2-v2/blob/master/Decidir/AdminPlanesCuotas/Model/Descuento.php#L109

No estoy seguro de como afecta esto a la implementación. Pero estaría bueno revisarlo para evitar problemas similares.

**Comment by marcosvolpiok** [comment]
Hola Matías. Buenas tardes.
Te consulto qué versión del plugin estás utilizando.

**Comment by matiasalvarez87** [comment]
Hola Marcos, 
Me costo encontrar como manejan las versiones del plugin en git ya que:

* No veo ninguna versión en los releases de git: https://github.com/decidir/plugin-magento2-v2/releases
* El composer.json nunca se modificó desde la primera versión

Vi que los manejan en los mensajes del commit: https://github.com/decidir/plugin-magento2-v2/commits/master

Las versiones actuales que estamos usando son:

**AdminPlanesCuotas**: 2.0.1
**SpsDecidir**: 2.0.2

Por lo que tengo entendido, el código del formateo de números no cambio en la última versión. Pero no estoy seguro si hay algún otro fix de esto en otro lado.  **Me podrías confirmar esto?**

_PD: Estaría bueno si pueden agregar un release notes, para poder entender mejor cuales con los features + fixes que agregan en cada versión. La mayoría de los cambios que vi en los últimos commits están relacionados a Cyber Source._

**Comment by drarko** [comment]
Estimado, acabamos de publicar un nuevo release, por favor probar con el mismo. Reabrir en caso de ser necesario. Gracias

**Comment by matiasalvarez87** [comment]
Gracias! Lo voy a estar testeando en los próximos días.

**Comment by matiasalvarez87** [comment]
@drarko @marcosvolpiok muchas gracias por publicar el release! https://github.com/decidir/plugin-magento2-v2/releases/tag/V2.1.1

Si pueden, la próxima estaría genial agregar un archivo con los **release notes** o **changelog**. https://github.com/github-tools/github-release-notes

Eso haría mucho más fácil entender cuales fueron los cambios realizados en la nueva versión :)
